// Code generated by ranges/internal/gen; DO NOT EDIT.
// To refresh, run: go generate ./ranges/...

package ranges

// Cloudflare's published IP ranges.
//
// Source: https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6
//
// SECURITY: this is a static snapshot; see the package documentation for why a
// stale list is risky. For guaranteed-current ranges, use the Cloudflare API:
// https://api.cloudflare.com/#cloudflare-ips-properties
var Cloudflare = []string{
	// IPv4
	"103.21.244.0/22",
	"103.22.200.0/22",
	"103.31.4.0/22",
	"104.16.0.0/13",
	"104.24.0.0/14",
	"108.162.192.0/18",
	"131.0.72.0/22",
	"141.101.64.0/18",
	"162.158.0.0/15",
	"172.64.0.0/13",
	"173.245.48.0/20",
	"188.114.96.0/20",
	"190.93.240.0/20",
	"197.234.240.0/22",
	"198.41.128.0/17",

	// IPv6
	"2400:cb00::/32",
	"2405:8100::/32",
	"2405:b500::/32",
	"2606:4700::/32",
	"2803:f800::/32",
	"2a06:98c0::/29",
	"2c0f:f248::/32",
}
